name: DVWA CI/CD

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master

jobs:

  build-and-analyze:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Validate PHP syntax
      run: |
        find . -name "*.php" -exec php -l {} \;

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Check Quality Gate
      uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
